import type { EntityTypesRegistry, ProjectTypesRegistry } from "../interfaces";

export const DEFAULT_PROJECT_TYPES: ProjectTypesRegistry = {
  operational: {
    id: "operational",
    name: "Operational",
    description: "Default ProjectFlow structure for active projects.",
    folderStructure: [
      "References",
      "Meetings",
      "Work",
      "Work/Tasks",
      "Work/Sprints",
      "Work/Ideas",
      "People",
    ],
    initialNotes: [
      { fileName: "${PROJECT_FULL_NAME}.md", template: "operational/project.md" },
      { fileName: "${PROJECT_NAME} Meetings.md", template: "operational/meetings.md" },
      { fileName: "${PROJECT_NAME} People.md", template: "operational/people.md" },
      { fileName: "${PROJECT_NAME} Work.md", template: "operational/work.md" },
      { fileName: "${PROJECT_NAME} References.md", template: "operational/references.md" },
    ],
    projectEntities: {
      task: {
        id: "task",
        name: "Task",
        templatePath: "operational/template-task.md",
        targetFolder: "Work/Tasks",
        filenameRule: "${PROJECT_ID}-${taskIndex}-${title}",
        patchMarkers: ["AI:CONTENT", "AI:ACTIONS"],
        fields: {
          title:       { type: "string", required: true, role: "title" },
          description: { type: "string", required: true },
          taskIndex:   { type: "number", role: "index" },
          sprint: {
            type: "reference", required: true,
            refersTo: { kind: "entity", entityType: "sprint" },
            description: "The sprint this task belongs to.",
            resolveHint: "Call listProjectFiles with subfolder='Work/Sprints'; use the filename without .md.",
          },
        },
      },
      "meeting.planning": {
        id: "meeting.planning",
        name: "Meeting (Planning)",
        templatePath: "operational/template-meeting-planning.md",
        targetFolder: "Meetings/Planning",
        filenameRule: "${DATE} ${title}",
        patchMarkers: ["AI:AGENDA", "AI:NOTES", "AI:ACTIONS"],
        fields: {
          title: { type: "string", required: true, role: "title" },
        },
      },
      "meeting.refinement": {
        id: "meeting.refinement",
        name: "Meeting (Refinement)",
        templatePath: "operational/template-meeting-refinement.md",
        targetFolder: "Meetings/Refinement",
        filenameRule: "${DATE} ${title}",
        patchMarkers: ["AI:AGENDA", "AI:NOTES", "AI:ACTIONS"],
        fields: {
          title: { type: "string", required: true, role: "title" },
        },
      },
      "meeting.retro": {
        id: "meeting.retro",
        name: "Meeting (Retro)",
        templatePath: "operational/template-meeting-retro.md",
        targetFolder: "Meetings/Retro",
        filenameRule: "${DATE} ${title}",
        patchMarkers: ["AI:AGENDA", "AI:NOTES", "AI:ACTIONS"],
        fields: {
          title: { type: "string", required: true, role: "title" },
        },
      },
      "meeting.demo": {
        id: "meeting.demo",
        name: "Meeting (Demo)",
        templatePath: "operational/template-meeting-demo.md",
        targetFolder: "Meetings/Demo",
        filenameRule: "${DATE} ${title}",
        patchMarkers: ["AI:AGENDA", "AI:NOTES", "AI:ACTIONS"],
        fields: {
          title: { type: "string", required: true, role: "title" },
        },
      },
      "meeting.daily": {
        id: "meeting.daily",
        name: "Meeting (Daily)",
        templatePath: "operational/template-meeting-daily.md",
        targetFolder: "Meetings/Daily",
        filenameRule: "${DATE} ${title}",
        patchMarkers: ["AI:AGENDA", "AI:NOTES", "AI:ACTIONS"],
        fields: {
          title: { type: "string", required: true, role: "title" },
        },
      },
      "meeting.knowledge": {
        id: "meeting.knowledge",
        name: "Meeting (Knowledge)",
        templatePath: "operational/template-meeting-knowledge.md",
        targetFolder: "Meetings/Knowledge",
        filenameRule: "${DATE} ${title}",
        patchMarkers: ["AI:AGENDA", "AI:NOTES", "AI:ACTIONS"],
        fields: {
          title: { type: "string", required: true, role: "title" },
        },
      },
      sprint: {
        id: "sprint",
        name: "Sprint",
        templatePath: "operational/template-sprint.md",
        targetFolder: "Work/Sprints",
        filenameRule: "Sprint ${title}",
        patchMarkers: ["AI:CONTENT", "AI:ACTIONS"],
        fields: {
          title: {
            type: "string", required: true, role: "title",
            description: "Short sprint identifier only — e.g. '1', '2', 'Q1 2024', 'March Week 1'. Do NOT include the project name or the word 'Sprint'.",
          },
          startedAt:  { type: "date", default: "today" },
          finishedAt: { type: "date", default: "today+14d" },
        },
      },
      idea: {
        id: "idea",
        name: "Idea",
        templatePath: "operational/template-idea.md",
        targetFolder: "Work/Ideas",
        filenameRule: "Idea ${title}",
        patchMarkers: ["AI:CONTENT"],
        fields: {
          title: { type: "string", required: true, role: "title" },
        },
      },
      reference: {
        id: "reference",
        name: "Reference",
        templatePath: "operational/template-reference-item.md",
        targetFolder: "References",
        filenameRule: "${title}",
        patchMarkers: ["AI:CONTENT", "AI:SUMMARY"],
        fields: {
          title: { type: "string", required: true, role: "title" },
        },
      },
    } as EntityTypesRegistry,
  },
  learning: {
    id: "learning",
    name: "Course / Learning",
    description: "Structured progression for courses, certifications, or self-learning.",
    folderStructure: [
      "Overview",
      "Modules",
      "Notes",
      "Assignments",
      "Reviews",
      "Resources",
      "References",
    ],
    initialNotes: [
      { fileName: "${PROJECT_FULL_NAME}.md", template: "learning/project.md" },
      { fileName: "${PROJECT_NAME} Modules.md", template: "learning/modules.md" },
      { fileName: "${PROJECT_NAME} Knowledge Base.md", template: "learning/knowledge-base.md" },
      { fileName: "Overview/Roadmap.md", template: "learning/roadmap.md" },
      { fileName: "Overview/Resources.md", template: "learning/resources.md" },
      { fileName: "Overview/Goals.md", template: "learning/goals.md" },
      { fileName: "Resources/ReadingList.md", template: "learning/reading-list.md" },
      { fileName: "Resources/References.md", template: "learning/references.md" },
    ],
    projectEntities: {
      module: {
        id: "module",
        name: "Module",
        templatePath: "learning/template-module.md",
        targetFolder: "Modules/${title}",
        filenameRule: "${title}",
        patchMarkers: ["AI:CONTENT", "AI:OBJECTIVES", "AI:SUMMARY"],
        childFolders: ["Lessons", "Notes", "Assignments", "Reviews"],
        fields: {
          title: { type: "string", required: true, role: "title" },
        },
      },
      lesson: {
        id: "lesson",
        name: "Lesson",
        templatePath: "learning/template-lesson.md",
        targetFolder: "${parentFolder}/Lessons/${title}",
        filenameRule: "${title}",
        patchMarkers: ["AI:CONTENT", "AI:NOTES", "AI:SUMMARY"],
        childFolders: ["Notes", "Assignments", "Reviews"],
        fields: {
          title: { type: "string", required: true, role: "title" },
          parentFolder: {
            type: "string", required: true, role: "parentFolder",
            allowedParents: ["module", "project"],
            description: "Existing folder path within the project. Use a module folder (e.g. 'Modules/Module 1 - Intro') or '' for project root. Call listProjectFiles with subfolder='Modules' to discover available folders. The system automatically appends /Lessons/{title}.",
          },
        },
      },
      note: {
        id: "note",
        name: "Note",
        templatePath: "learning/template-note.md",
        targetFolder: "${parentFolder}/Notes",
        filenameRule: "${DATE} ${title}",
        patchMarkers: ["AI:CONTENT", "AI:SUMMARY"],
        fields: {
          title: { type: "string", required: true, role: "title" },
          parentFolder: {
            type: "string", required: true, role: "parentFolder",
            allowedParents: ["module", "lesson", "project", "assignment", "review"],
            description: "Existing folder path within the project. Call listProjectFiles with subfolder='Modules' to discover available folders. Use '' for project root.",
          },
        },
      },
      assignment: {
        id: "assignment",
        name: "Assignment",
        templatePath: "learning/template-assignment.md",
        targetFolder: "${parentFolder}/Assignments",
        filenameRule: "Assignment ${title}",
        patchMarkers: ["AI:CONTENT", "AI:REQUIREMENTS", "AI:SUBMISSION"],
        fields: {
          title: { type: "string", required: true, role: "title" },
          parentFolder: {
            type: "string", required: true, role: "parentFolder",
            allowedParents: ["module", "lesson", "project"],
            description: "Existing folder path within the project. Call listProjectFiles with subfolder='Modules' to discover available folders. Use '' for project root.",
          },
        },
      },
      review: {
        id: "review",
        name: "Review",
        templatePath: "learning/template-review.md",
        targetFolder: "${parentFolder}/Reviews",
        filenameRule: "${DATE} Review ${title}",
        patchMarkers: ["AI:CONTENT", "AI:REFLECTION", "AI:ACTIONS"],
        fields: {
          title: { type: "string", required: true, role: "title" },
          parentFolder: {
            type: "string", required: true, role: "parentFolder",
            allowedParents: ["project", "module", "lesson", "assignment"],
            description: "Existing folder path within the project. Call listProjectFiles with subfolder='Modules' to discover available folders. Use '' for project root.",
          },
        },
      },
      reference: {
        id: "reference",
        name: "Reference",
        templatePath: "learning/template-reference-item.md",
        targetFolder: "References",
        filenameRule: "${title}",
        patchMarkers: ["AI:CONTENT", "AI:SUMMARY"],
        fields: {
          title: { type: "string", required: true, role: "title" },
        },
      },
    } as EntityTypesRegistry,
  },
};
