import type { EntityTypesRegistry, ProjectTypesRegistry } from "../interfaces";

export const DEFAULT_ENTITY_TYPES: Record<string, EntityTypesRegistry> = {
  operational: {
    task: {
      id: "task",
      name: "Task",
      templatePath: "operational/template-task.md",
      targetFolder: "Work/Tasks",
      filenameRule: "${PROJECT_ID}-${title}",
      requiredFields: ["title", "description"],
      patchMarkers: ["AI:CONTENT", "AI:ACTIONS"],
    },
    "meeting.planning": {
      id: "meeting.planning",
      name: "Meeting (Planning)",
      templatePath: "operational/template-meeting-planning.md",
      targetFolder: "Meetings",
      filenameRule: "${DATE} ${title}",
      requiredFields: ["title"],
      patchMarkers: ["AI:AGENDA", "AI:NOTES", "AI:ACTIONS"],
    },
    "meeting.refinement": {
      id: "meeting.refinement",
      name: "Meeting (Refinement)",
      templatePath: "operational/template-meeting-refinement.md",
      targetFolder: "Meetings",
      filenameRule: "${DATE} ${title}",
      requiredFields: ["title"],
      patchMarkers: ["AI:AGENDA", "AI:NOTES", "AI:ACTIONS"],
    },
    "meeting.retro": {
      id: "meeting.retro",
      name: "Meeting (Retro)",
      templatePath: "operational/template-meeting-retro.md",
      targetFolder: "Meetings",
      filenameRule: "${DATE} ${title}",
      requiredFields: ["title"],
      patchMarkers: ["AI:AGENDA", "AI:NOTES", "AI:ACTIONS"],
    },
    "meeting.demo": {
      id: "meeting.demo",
      name: "Meeting (Demo)",
      templatePath: "operational/template-meeting-demo.md",
      targetFolder: "Meetings",
      filenameRule: "${DATE} ${title}",
      requiredFields: ["title"],
      patchMarkers: ["AI:AGENDA", "AI:NOTES", "AI:ACTIONS"],
    },
    "meeting.daily": {
      id: "meeting.daily",
      name: "Meeting (Daily)",
      templatePath: "operational/template-meeting-daily.md",
      targetFolder: "Meetings",
      filenameRule: "${DATE} ${title}",
      requiredFields: ["title"],
      patchMarkers: ["AI:AGENDA", "AI:NOTES", "AI:ACTIONS"],
    },
    "meeting.knowledge": {
      id: "meeting.knowledge",
      name: "Meeting (Knowledge)",
      templatePath: "operational/template-meeting-knowledge.md",
      targetFolder: "Meetings",
      filenameRule: "${DATE} ${title}",
      requiredFields: ["title"],
      patchMarkers: ["AI:AGENDA", "AI:NOTES", "AI:ACTIONS"],
    },
    sprint: {
      id: "sprint",
      name: "Sprint",
      templatePath: "operational/template-sprint.md",
      targetFolder: "Work",
      filenameRule: "${title}",
      requiredFields: ["title"],
      fieldDefaults: {
        startedAt: "today",
        finishedAt: "today+14d",
      },
      patchMarkers: ["AI:CONTENT", "AI:ACTIONS"],
    },
    idea: {
      id: "idea",
      name: "Idea",
      templatePath: "operational/template-idea.md",
      targetFolder: "Knowledge Base",
      filenameRule: "Idea ${title}",
      requiredFields: ["title"],
      patchMarkers: ["AI:CONTENT"],
    },
  },
  learning: {
    module: {
      id: "module",
      name: "Module",
      templatePath: "learning/template-module.md",
      targetFolder: "Modules/${title}",
      filenameRule: "${title}",
      requiredFields: ["title"],
      patchMarkers: ["AI:CONTENT", "AI:OBJECTIVES", "AI:SUMMARY"],
      childFolders: ["Lessons", "Notes", "Assignments", "Reviews"],
    },
    lesson: {
      id: "lesson",
      name: "Lesson",
      templatePath: "learning/template-lesson.md",
      targetFolder: "${parentFolder}/Lessons/${title}",
      filenameRule: "${title}",
      requiredFields: ["title", "parentFolder", "module"],
      patchMarkers: ["AI:CONTENT", "AI:NOTES", "AI:SUMMARY"],
      childFolders: ["Notes", "Assignments", "Reviews"],
    },
    note: {
      id: "note",
      name: "Note",
      templatePath: "learning/template-note.md",
      targetFolder: "${parentFolder}/Notes",
      filenameRule: "${DATE} ${title}",
      requiredFields: ["title", "parentFolder"],
      patchMarkers: ["AI:CONTENT", "AI:SUMMARY"],
    },
    assignment: {
      id: "assignment",
      name: "Assignment",
      templatePath: "learning/template-assignment.md",
      targetFolder: "${parentFolder}/Assignments",
      filenameRule: "Assignment ${title}",
      requiredFields: ["title", "parentFolder"],
      patchMarkers: ["AI:CONTENT", "AI:REQUIREMENTS", "AI:SUBMISSION"],
    },
    review: {
      id: "review",
      name: "Review",
      templatePath: "learning/template-review.md",
      targetFolder: "${parentFolder}/Reviews",
      filenameRule: "${DATE} Review ${title}",
      requiredFields: ["title", "parentFolder"],
      patchMarkers: ["AI:CONTENT", "AI:REFLECTION", "AI:ACTIONS"],
    },
  },
};

export const DEFAULT_PROJECT_TYPES: ProjectTypesRegistry = {
  operational: {
    id: "operational",
    name: "Operational",
    description: "Default ProjectFlow structure for active projects.",
    folderStructure: [
      "Knowledge Base",
      "Meetings",
      "Work",
      "Work/Tasks",
      "People",
    ],
    initialNotes: [
      { fileName: "${PROJECT_FULL_NAME}.md", template: "operational/project.md" },
      { fileName: "${PROJECT_NAME} Meetings.md", template: "operational/meetings.md" },
      { fileName: "${PROJECT_NAME} People.md", template: "operational/people.md" },
      { fileName: "${PROJECT_NAME} Work.md", template: "operational/work.md" },
      { fileName: "${PROJECT_NAME} Knowledge Base.md", template: "operational/knowledge-base.md" },
    ],
    projectTemplates: [
      { source: "operational/template-meeting-daily.md", target: "${PROJECT_NAME}_Meeting_Daily_Template.md" },
      { source: "operational/template-meeting-discussion.md", target: "${PROJECT_NAME}_Meeting_Discussion_Template.md" },
      { source: "operational/template-meeting-knowledge.md", target: "${PROJECT_NAME}_Meeting_Knowledge_Template.md" },
      { source: "operational/template-meeting-planning.md", target: "${PROJECT_NAME}_Meeting_Planning_Template.md" },
      { source: "operational/template-meeting-refinement.md", target: "${PROJECT_NAME}_Meeting_Refinement_Template.md" },
      { source: "operational/template-meeting-retro.md", target: "${PROJECT_NAME}_Meeting_Retro_Template.md" },
      { source: "operational/template-meeting-demo.md", target: "${PROJECT_NAME}_Meeting_Demo_Template.md" },
      { source: "operational/template-sprint.md", target: "${PROJECT_NAME}_Sprint_Template.md" },
      { source: "operational/template-task.md", target: "${PROJECT_NAME}_Task_Template.md" },
      { source: "operational/template-idea.md", target: "${PROJECT_NAME}_Idea_Template.md" },
      { source: "operational/template-knowledge-base-item.md", target: "${PROJECT_NAME}_Knowledge_Item_Template.md" },
    ],
    allowedEntityTypes: Object.keys(DEFAULT_ENTITY_TYPES),
  },
  learning: {
    id: "learning",
    name: "Course / Learning",
    description: "Structured progression for courses, certifications, or self-learning.",
    folderStructure: [
      "Overview",
      "Modules",
      "Notes",
      "Assignments",
      "Reviews",
      "Resources",
    ],
    initialNotes: [
      { fileName: "${PROJECT_FULL_NAME}.md", template: "learning/project.md" },
      { fileName: "${PROJECT_NAME} Modules.md", template: "learning/modules.md" },
      { fileName: "${PROJECT_NAME} Knowledge Base.md", template: "learning/knowledge-base.md" },
      { fileName: "Overview/Roadmap.md", template: "learning/roadmap.md" },
      { fileName: "Overview/Resources.md", template: "learning/resources.md" },
      { fileName: "Overview/Goals.md", template: "learning/goals.md" },
      { fileName: "Resources/ReadingList.md", template: "learning/reading-list.md" },
      { fileName: "Resources/References.md", template: "learning/references.md" },
    ],
    projectTemplates: [
      { source: "learning/template-module.md", target: "${PROJECT_NAME}_Module_Template.md" },
      { source: "learning/template-lesson.md", target: "${PROJECT_NAME}_Lesson_Template.md" },
      { source: "learning/template-assignment.md", target: "${PROJECT_NAME}_Assignment_Template.md" },
      { source: "learning/template-note.md", target: "${PROJECT_NAME}_Note_Template.md" },
      { source: "learning/template-review.md", target: "${PROJECT_NAME}_Review_Template.md" },
      { source: "learning/custom-review.md", target: "${PROJECT_NAME}_Custom_Review_Template.md" },
    ],
    allowedEntityTypes: ["module", "lesson", "note", "assignment", "review"],
  },
};
